package cs3500.pa03.model;

import cs3500.pa03.view.GameViewer;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Responsible for implementing Player for an AI player
 */
public class AIPlayer extends AbstractPlayer {
  /**
   * @return AI for AI player
   */
  public String name() {
    return "AI";
  }

  /**
   * Generates a list of shots

   * @return a list of shots generated by the AI
   */
  public List<Coord> takeShots() {
    GameViewer view = new GameViewer();
    System.out.println("Opponent board data:");
    view.printBoard(super.board.getLetters(), true);

    Random r = new Random();
    int shots = super.board.getAliveShips();
    int width = super.board.getLetters().length;
    int height = super.board.getLetters()[0].length;
    int x;
    int y;
    List<Coord> coords = new ArrayList<>();

    for (int i = 0; i < shots; i += 1) {
      x = r.nextInt(width);
      y = r.nextInt(height);
      while (super.alreadyShot[x][y]) {
        x = r.nextInt(width);
        y = r.nextInt(height);
      }
      super.alreadyShot[x][y] = true;
      coords.add(new Coord(x, y));
    }

    return coords;
  }
}
